name: Cancel workflows on status failure

on:
  status:

permissions:
  actions: write
  contents: read

jobs:
  cancel-on-failure:
    name: Cancel General Checks on Failure
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero' && (github.event.state == 'failure' || github.event.state == 'error')
    steps:
      - name: Find workflows to cancel
        id: find-workflows
        run: |
          echo "Status event details:"
          echo "SHA: ${{ github.event.sha }}"
          echo "State: ${{ github.event.state }}"
          echo "Context: ${{ github.event.context }}"

          # Get all workflow runs for the specific SHA
          workflow_runs=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?head_sha=${{ github.event.sha }}")

          # Find running general.yml workflows on merge queue branches
          current_run_id="${{ github.run_id }}"
          matching_runs=$(echo "$workflow_runs" | jq -r --arg current_run "$current_run_id" '.workflow_runs[] | select(.path == ".github/workflows/general.yml" and .status != "completed" and (.head_branch // "" | test("^gh-readonly-queue/main/pr-")) and (.id | tostring) != $current_run) | "\(.id) \(.head_branch)"')

          if [ -n "$matching_runs" ]; then
            echo "Found workflows to cancel:"
            echo "$matching_runs"
            echo "workflows<<EOF" >> $GITHUB_OUTPUT
            echo "$matching_runs" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "No matching workflows found to cancel"
            echo "workflows=" >> $GITHUB_OUTPUT
          fi

      - name: Cancel workflows
        if: steps.find-workflows.outputs.workflows != ''
        run: |
          echo "Cancelling workflows..."
          echo "${{ steps.find-workflows.outputs.workflows }}" | while read -r run_id branch; do
            if [ -n "$run_id" ]; then
              echo "Cancelling general.yml workflow run $run_id on branch $branch for SHA ${{ github.event.sha }}"
              curl -X POST -H "Authorization: Bearer ${{ github.token }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel"
            fi
          done
